language: csharp
dist: trusty
notifications:
  email: never
mono: none
dotnet: 1.0.1
script:
  - dotnet restore -v Minimal
  - dotnet build src/TinyPNG/TinyPNG.csproj -c Release -f netstandard1.3
  - dotnet test tests/TinyPng.Tests/TinyPng.Tests.csproj
